site_name: Suliangzai's Wiki
site_author: Suliangzai
copyright: "© 2024 <a herf='https://github.com/suliangzai/Note'>Suliangzai</a>. All rights reserved."
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - Home: home.md
  - About:
      - Overview: about/overview.md
      - Team: about/team.md
  - Features:
      - mkdocs: features/index.md
  - Contacts: contact.md

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/suliangzai
  - icon: fontawesome/brands/twitter
    link: https://github.com/suliangzai/Note
  - icon: fontawesome/brands/instagram
    link: https://github.com/suliangzai/Note
  - icon: fontawesome/brands/telegram
    link: https://github.com/suliangzai/Note
  - icon: fontawesome/brands/weixin
    link: https://github.com/suliangzai/Note
  - icon: fontawesome/brands/qq
    link: https://github.com/suliangzai/Note

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg